name: 'Architecture Guardian'
description: 'Run archguardian to check for security issues, AI code smells, and convention violations'
inputs:
  config:
    description: 'Path to .archguard.yml config file'
    required: false
    default: '.archguard.yml'
  format:
    description: 'Output format (terminal, json, sarif)'
    required: false
    default: 'sarif'
  fail-on:
    description: 'Minimum severity to fail the check (error, warning, info)'
    required: false
    default: 'error'
  quality-gate:
    description: 'Enable quality gate thresholds'
    required: false
    default: 'false'
  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'true'
  post-to-pr:
    description: 'Post findings as inline PR review comments'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install archguardian
      shell: bash
      run: npm install -g archguardian
    - name: Run archguardian scan
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        ARGS="--format ${{ inputs.format }} --ci github"
        if [ "${{ inputs.quality-gate }}" = "true" ]; then
          ARGS="$ARGS --quality-gate"
        fi
        if [ "${{ inputs.post-to-pr }}" = "true" ]; then
          ARGS="$ARGS --post-to-pr"
        fi
        archguardian scan $ARGS
    - name: Upload SARIF
      if: inputs.upload-sarif == 'true' && inputs.format == 'sarif' && always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: archguardian-results.sarif
